### ISSUE TITLE
Is the project down for good?

### ISSUE THREAD

**Issue by e-kotov** [bsc-flowmaps/flowmaps-data#1]
Hello, I noticed that https://flowmaps.life.bsc.es/ now redirects to https://inb-elixir.es/ .
Are there any plans to resume the service?

**Comment by jmfernandez** [comment]
Dear @e-kotov , thanks for communicating us the issue! You have noticed a glitch in frontend setup after an internal migration of VMs, which seems fixed right now.

**Comment by e-kotov** [comment]
@jmfernandez great to see it live again!
